### ISSUE TITLE
Which device drivers are supported?

### ISSUE THREAD

**Issue by beriberikix** [AkihiroSuda/vde_vmnet#16]
Currently the instructions show using QEMU with `-device virtio-net-pci`. I'm thinking about using this project for embedded development based on the Zephyr RTOS which already has a QEMU integration. Depending on the target device, [different drivers](https://docs.zephyrproject.org/latest/guides/networking/qemu_eth_setup.html#basic-setup) are used by Zephyr, such as `e1000`. Is there a specific dependency on this configuration of virtio?  Apologies if that's a naive question, I'm rather new to QEMU networking.

**Comment by AkihiroSuda** [comment]
Should work with any Ethernet device
