### ISSUE TITLE
[vde_switch] No buffer space available

### ISSUE THREAD

**Issue by yuchanns** [AkihiroSuda/vde_vmnet#19]
Lima Version: 0.6

For creating a local k8s cluster I started two instance with --vmnet-mode=bridged specified for networking. After the initialization (by Kubeadm) of control-plane, node instance was expected to join the cluster.

Howerver, node instance kept stuck into NoReady status and I found the console of vde_switch kept printing "vde_switch: send_sockaddr port 3: No buffer space available".

I tried to increase `wmem_max` using: 
```sh
echo 83886080 | sudo tee /proc/sys/net/core/wmem_max
```
But nothing resolved.

I wonder if this is a bug?

```sh
$ sudo vde_vmnet --vmnet-mode=bridged --vmnet-interface=en0 /tmp/vde.ctl
Initializing vmnet.framework (mode 1002)
Using network interface "en0"
* vmnet_mtu: 1500
* vmnet_interface_id: CD65D0DC-6BC7-4E0F-9F31-FD8A255DDD3E
* vmnet_max_packet_size: 1514
* vmnet_mac_address: 72:7e:fd:a5:36:a7
```
```sh
$ vde_switch
vde_switch: send_sockaddr port 3: No buffer space available
vde_switch: send_sockaddr port 3: No buffer space available
vde_switch: send_sockaddr port 3: No buffer space available
vde_switch: send_sockaddr port 3: No buffer space available
```

**Comment by AkihiroSuda** [comment]
"Switchless mode" may work as a workaround
https://github.com/lima-vm/vde_vmnet/tree/v0.4.0#ptp-mode-switchless-mode
https://github.com/lima-vm/lima/blob/v0.6.0/pkg/limayaml/default.yaml#L133

**Comment by yuchanns** [comment]
> "Switchless mode" may work as a workaround
> [https://github.com/lima-vm/vde_vmnet/tree/v0.4.0#ptp-mode-switchless-mode](https://github.com/lima-vm/vde_vmnet/tree/v0.4.0?rgh-link-date=2021-08-22T18%3A37%3A52Z#ptp-mode-switchless-mode)
> [https://github.com/lima-vm/lima/blob/v0.6.0/pkg/limayaml/default.yaml#L133](https://github.com/lima-vm/lima/blob/v0.6.0/pkg/limayaml/default.yaml?rgh-link-date=2021-08-22T18%3A37%3A52Z#L133)

```sh
$ sudo vde_vmnet /tmp/vde.ptp[]
zsh: no matches found: /tmp/vde.ptp[]
```
Did I missed anything?

Also, I notice that readme said the ptp mode doesn't support multi vm

**Comment by AkihiroSuda** [comment]
> Did I missed anything?

I don't know about zsh, but you'll probably have to escape the brackets

> Also, I notice that readme said the ptp mode doesn't support multi vm

That description is for shared mode.
Should work for multi-VM with bridged mode (untested).

**Comment by rupesh-papneja** [comment]
I am also facing the same issue. I am testing lima-vm and creating k3s agent on mac M1, which I want to connect to another system on host network. (k3s-sever on existing linux box)

Is there a way for the VMs created be assigned the IP address from the host network and be discoverable. bridged mode is not working as I thought it would. 

Tried the command 
`sudo vde_vmnet /tmp/vde.ptp[]`

getting below message:
vde_send: Destination address required

**Comment by AkihiroSuda** [comment]
cc @jandubois

**Comment by rupesh-papneja** [comment]
I have been able to connect the k3s linux master and k3s agent running via lima  in bridged mode on M1 mac.

After creating the VM via limactl, bridge network is created. Identified it and manually bridged the "bridge" network, like bridge100 to the interface that is allocating ip to the host machine like on en1.
`sudo ifconfig bridge100 addm en1`

After that, restarted the k3s agent supplying the flag --node-ip (host-network ip) and also set '--flannel-iface' to point to the right host network interface.
