### ISSUE TITLE
Include a tarball with pre-compiled binaries in vde_vmnet releases

### ISSUE THREAD

**Issue by jandubois** [AkihiroSuda/vde_vmnet#22]
The tarball should include both `vde_switch` and `vde_vmnet` binaries with an `/opt/vde` prefix compiled in.

**Comment by AkihiroSuda** [comment]
Help wanted, for cross compilation on GHA

**Comment by jandubois** [comment]
> Help wanted, for cross compilation on GHA

I forgot that there are no M1 runners.

I don't think cross-compiling `vde-2` (to get `vde_switch` and `libvdeplug.3.dylib`) is feasible.

What do you think about just having a script to manually build release artifacts for now?

**Comment by AkihiroSuda** [comment]
> I don't think cross-compiling vde-2 (to get vde_switch and libvdeplug.3.dylib) is feasible.

Why? I didn't test, but I _guess_ `CFLAGS="-target arm64-macos" LDFLAGS="-target arm64-macos"` should work.

**Comment by jandubois** [comment]
> Why? I didn't test, but I _guess_ `CFLAGS="-target arm64-macos" LDFLAGS="-target arm64-macos"` should work.

Sorry, I didn't try either. I just assumed that `autoconf` and cross-compilation on macOS don't mix, but it looks like I'm wrong.

I had to delete `/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk` to get the compiler to use the 11.1 headers, and I also had to add `--host x86_64`, but am still seeing compile errors:

```
realloc.c:17:10: error: implicit declaration of function 'rpl_malloc' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                return malloc(size);
                       ^
../../include/config.h:349:16: note: expanded from macro 'malloc'
#define malloc rpl_malloc
               ^
```

Will look some more tommorrow, but maybe auditing compiler warnings/errors even for the Intel build is worthwhile:

```
tcp_subr.c:341:4: warning: 'strncpy' will always overflow; destination buffer has size 104, but size argument is 108 [-Wbuiltin-memcpy-chk-size]
                        strncpy(addr.sun_path,path,UNIX_PATH_MAX);
                        ^
```

It looks like the code doesn't pick up the Darwin definition of `UNIX_PATH_MAX` and uses the default value defined in `slirpvde/tcp2unix.h`.

**Comment by AkihiroSuda** [comment]
Thanks for testing. We don't need slirpvde.

**Comment by jandubois** [comment]
vde_vmnet is now deprecated
