### ISSUE TITLE
Build an installer that can be installed as a brew cask

### ISSUE THREAD

**Issue by jandubois** [AkihiroSuda/vde_vmnet#23]
Homebrew casks are just wrappers around regular macOS installers (typically `*.dmg` or `*.pkg`), that can install anywhere, and that can require `sudo` during installation.

We need an installer that can take the tarball created by #22 and install it into `/opt/vde`.

Let's find out if we can use an [installer script](https://docs.brew.sh/Cask-Cookbook#installer-script) with just a tarball instead of a full-blown DMG or PKG installer.

We should probably also [create our own tap](https://docs.brew.sh/How-to-Create-and-Maintain-a-Tap) to host the cask, at least initially.

**Comment by brad-x** [comment]
Question - I made a MacPorts port out of this fairly easily, and it'd remove needed work to build a .pkg if brew built it from source wouldn't it?

**Comment by brad-x** [comment]
> Question - I made a MacPorts port out of this fairly easily, and it'd remove needed work to build a .pkg if brew built it from source wouldn't it?

Answering my own question, this is only easy if brew has a package for the latest vde-2 commit hash. Ignore me.

Perhaps a brew tap including a vde formula for the current latest commit?

**Comment by jandubois** [comment]
vde_vmnet is now deprecated
