### ISSUE TITLE
Networking speeds are slow, is this expected?

### ISSUE THREAD

**Issue by gigatexal** [AkihiroSuda/vde_vmnet#26]
Firstly, kudos to this project, it has saved me hours of fiddling with networking myself. I couldn't get the tap and bridge stuff working using older guides and found this when Limactl hit the top of HN.

This isn't a complaint more a expectations check.

I've a 400mbit internet connection and generally see downloads of `10+MB/s`. I followed the guide to get networking on qemu on MacOSX working and buil the tool using the latest master branch (current top commit `14e1c9e06f4dbdddc6fe4e85fc72a1d583b049ad`) and am seeing downloads of this:

`72.2 kB/s 19min 46s` while doing an apt-get of various libraries.

So the question is, is there anything that can be done to speed this up? or is this expected behaivor?

Below is the qemu script I use to start my VM:

```
qemu-system-x86_64 \
  -m 8G \
  -vga virtio \
  -display default,show-cursor=on \
  -usb \
  -device usb-tablet \
  -machine type=q35,accel=hvf \
  -smp 4 \
  -device virtio-net-pci,netdev=net0 -netdev vde,id=net0,sock=/var/run/vde.ctl \
  -drive file=./disks/ubuntu.qcow2,if=virtio \
  -cpu Nehalem
```

I should note that iperf3 showed speeds of 41mbits from the MacOS host and this VM. 

output of configure:

```
Configure results:

 - VDE CryptCab............ disabled
 + VDE Router.............. enabled
 - TAP support............. disabled
 + pcap support............ enabled
 - Experimental features... disabled
 - Profiling options....... disabled
```

**Comment by AkihiroSuda** [comment]
PTP mode might be faster https://github.com/lima-vm/vde_vmnet/tree/v0.5.0#ptp-mode-switchless-mode

**Comment by AkihiroSuda** [comment]
Or you might be hitting this https://gitlab.com/qemu-project/qemu/-/issues/334 (“macOS App Nap feature gradually freezes QEMU process”)

**Comment by gigatexal** [comment]
> Or you might be hitting this https://gitlab.com/qemu-project/qemu/-/issues/334 (“macOS App Nap feature gradually freezes QEMU process”)

I saw something that I think might have been related to this in the QEMU output saying that one of the cores was stalled... I will look into that.

Thanks for the suggestion about ptp I will try that.

**Comment by gigatexal** [comment]
> PTP mode might be faster https://github.com/lima-vm/vde_vmnet/tree/v0.5.0#ptp-mode-switchless-mode

Where can I learn more about PTP mode? Would this allow the host to still talk to the guest over some ports? i.e ssh and 8080 (for web stuff)?

**Comment by AkihiroSuda** [comment]
> Would this allow the host to still talk to the guest over some ports? i.e ssh and 8080 (for web stuff)?

Yes

**Comment by gigatexal** [comment]
Wow, disabled AppNap globally and got this getting the Linux kernel:

```
linux-5.14.tar.xz                   55%[==================================>                             ]  63.71M  1.52MB/s    eta 36s
```

but apt installing zsh for example only nets me 68KB/s... I guess it could be a combination of issues.

Will try this in conjunction with PTP.

**Comment by gigatexal** [comment]
PTP works fast enough for this to be useful to me, thank you so much for the suggestion!
