### ISSUE TITLE
Cross-compile vde_vmnet for ARM target

### ISSUE THREAD

**Issue by AkihiroSuda** [AkihiroSuda/vde_vmnet#5]
```console
$ CFLAGS="-target arm64-macos" LDFLAGS="-target arm64-macos" make
cc -target arm64-macos -DVERSION=\"v0.1.0\" -c cli.c -o cli.o
cc -target arm64-macos -DVERSION=\"v0.1.0\" -c main.c -o main.o
cc -target arm64-macos -DVERSION=\"v0.1.0\" -o vde_vmnet -target arm64-macos -lvdeplug -framework vmnet  cli.o  main.o
ld: warning: ignoring file /usr/local/lib/libvdeplug.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_vde_close", referenced from:
      _main in main.o
  "_vde_open_real", referenced from:
      _main in main.o
  "_vde_recv", referenced from:
      _main in main.o
  "_vde_send", referenced from:
      __on_vmnet_packets_available in main.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [vde_vmnet] Error 1
```

**Comment by reishoku** [comment]
Cross-compilation for arm64 target on x86_64 host can be done as follows:

1. (optional? not clear) Install Xcode (not Xcode Command Line Tools)
2.  `git clone https://github.com/virtualsquare/vde-2.git`
3. `cd vde-2`
4. `export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)`
5. `export CC=$(xcrun --sdk macosx --find clang)`
6. `export CXX=$(xcrun --sdk macosx --find clang++)`
7. `export CFLAGS="-arch arm64e -isysroot $SDKROOT -Wno-error=implicit-function-declaration"`
8. `export CXXFLAGS=$CFLAGS`
9. `./configure --prefix=/opt/vde --host=arm-apple-darwin --target=arm-apple-darwin --build=x86_64-apple-darwin`
10. `make -j3 V=1`
11. `sudo make install PREFIX=/opt/vde`
12. `git clone https://github.com/lima-vm/vde_vmnet`
13. `cd vde_vmnet`
14. `make PREFIX=/opt/vde`
15. `sudo make PREFIX=/opt/vde install`
16. Done.

------------------------------------------------------------------
FAT binary (x86_64 and arm64 binary in one file) can created as follows **not tested**:

1. (optional? not clear) Install Xcode (not Xcode Command Line Tools)
2.  `git clone https://github.com/virtualsquare/vde-2.git`
3. `cd vde-2`
4. `export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)`
5. `export CC=$(xcrun --sdk macosx --find clang)`
6. `export CXX=$(xcrun --sdk macosx --find clang++)`
7. `export CFLAGS="-arch arm64e -arch x86_64 -isysroot $SDKROOT -Wno-error=implicit-function-declaration"`
8. `export CXXFLAGS=$CFLAGS`
9. `./configure --prefix=/opt/vde
10. `make V=1`
11. `sudo make install PREFIX=/opt/vde`
12. `git clone https://github.com/lima-vm/vde_vmnet`
13. `cd vde_vmnet`
14. `make PREFIX=/opt/vde`
15. `sudo make PREFIX=/opt/vde install`
16. Done.

**Comment by network-shark** [comment]
Tried to compile but I got an error.

MacOS 12.2.1 on M1Pro
```
╰─ export SDKROOT=$(xcrun --sdk macosx --show-sdk-path);
export CC=$(xcrun --sdk macosx --find clang);
export CXX=$(xcrun --sdk macosx --find clang++);
export CFLAGS="-arch arm64e -arch x86_64 -isysroot $SDKROOT -Wno-error=implicit-function-declaration";
export CXXFLAGS=$CFLAGS;

 OSX  MacBook-Pro-von-Sebastian  sharky  ~/Downloads/vde-2   master                                                                                      30037
╰─ echo $SDKROOT
echo $CC
echo $CXX
echo $CFLAGS
echo $CXXFLAGS
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
/Library/Developer/CommandLineTools/usr/bin/clang
/Library/Developer/CommandLineTools/usr/bin/clang++
-arch arm64e -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -Wno-error=implicit-function-declaration
-arch arm64e -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -Wno-error=implicit-function-declaration
 OSX  MacBook-Pro-von-Sebastian  sharky  ~/Downloads/vde-2   master                                                                                      30038
╰─ `./configure --prefix=/opt/vde
bquote>
 OSX  MacBook-Pro-von-Sebastian  sharky  ~/Downloads/vde-2   master                                                                                      30038
╰─ echo $SDKROOT
echo $CC
echo $CXX
echo $CFLAGS
echo $CXXFLAGS
 OSX  MacBook-Pro-von-Sebastian  sharky  ~/Downloads/vde-2   master                                                                                      30038
╰─ ./configure --prefix=/opt/vde
configure: error: cannot find required auxiliary files: config.guess config.sub install-sh
```

**Comment by hftsai256** [comment]
> OSX  MacBook-Pro-von-Sebastian  sharky  ~/Downloads/vde-2   master                                                                                      30038
> ╰─ ./configure --prefix=/opt/vde
> configure: error: cannot find required auxiliary files: config.guess config.sub install-sh

You would have to run `autoreconf --install` to generate `configure` script

**Comment by jandubois** [comment]
vde_vmnet is now deprecated
